# WORLD_GENERATED
# CHUNK_LAST_LOADED
passed-time-calculation-mode: "WORLD_GENERATED"

growth-durations-minutes:
  {
    wheat: 34.93,
    beetroot: 20,
    potato: 5,
    carrot: 8,
    pumpkin: 20,
    melon: 20,
  }